[package]
name = "liana-connect"
version = "0.1.0"
authors = ["Edouard Paris <m@edouard.paris>"]
edition = "2018"
repository = "https://github.com/wizardsardine/liana"
license-file = "LICENCE"
keywords = ["bitcoin", "wallet", "miniscript", "inheritance", "recovery"]
description = "Liana Connect development kit"

[dependencies]
